inherit: 
    - models/small.yaml

model:
    family: gpt2_nn
    n_positions: 101
    n_in_intermediate: 0
    n_out_intermediate: 0
    hidden_sep_embed: False
    knot1: 1
    knot2: 2

training:
    data: gaussian
    task: relu_nn_regression
    task_kwargs: 
        mode: 'relu'
    batch_size: 64
    learning_rate: 0.0001
    save_every_steps: 1000
    keep_every_steps: 100000
    train_steps: 50000 # 500001
    multilayer:
        K: 2
        z_lr: 0.01 
        z_lb: 0.1
        epsilon: 0.5
        rho: 1
        
    curriculum:
        dims:
            start: 5
            end: 5
            inc: 1
            interval: 2000
